src/Entity/Atelier.php
<?php

namespace App\Entity;

use App\Repository\AtelierRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\User;
use function Sodium\add;

#[ORM\Entity(repositoryClass: AtelierRepository::class)]
class Atelier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\ManyToOne(inversedBy: 'ateliers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $nomInstructeur = null;

    #[ORM\Column(type: Types::ARRAY, nullable: true)]
    private array $apprentisInscrits = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getNomInstructeur(): ?User
    {
        return $this->nomInstructeur;
    }

    public function setNomInstructeur(?User $nomInstructeur): self
    {
        $this->nomInstructeur = $nomInstructeur;

        return $this;
    }

    public function getApprentisInscrits(): array
    {
        return $this->apprentisInscrits;
    }

    public function setApprentisInscrits(?array $apprentisInscrits): self
    {
        $this->apprentisInscrits = $apprentisInscrits;

        return $this;
    }

    public function addApprentiInscrit(?int $apprentiInscrit): void
    {


        array_push($this->apprentisInscrits, $apprentiInscrit);

    }

    public function removeApprentiInscrit(?int $apprentiInscrit): void
    {
        $key = array_search($apprentiInscrit, $this->apprentisInscrits);
        if ($key !== false) {
            unset($this->apprentisInscrits[$key]);
        }
    }
}

src/Form/AtelierType.php
<?php

namespace App\Form;

use App\Entity\Atelier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class AtelierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Description', TextareaType::class, [
                'label' => 'Description',
                'attr' => [
                    'rows' => 5,
                ],
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Atelier::class,
        ]);
    }
}

src/Controller/AtelierController.php
<?php

namespace App\Controller;

use App\Entity\Atelier;
use App\Form\AtelierType;
use App\Repository\AtelierRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\MesServices\MarkdownAtelier;

#[Route('/atelier')]
class AtelierController extends AbstractController
{

    #[Route('/accueil', name: 'app_atelier_accueil', methods: ['GET'])]
    public function accueil(): Response
    {
        return $this->render('atelier/accueil.html.twig');
    }

    #[Route('/', name: 'app_atelier_index', methods: ['GET'])]
    public function index(AtelierRepository $atelierRepository, MarkdownAtelier $markdownAtelier): Response
    {
        return $this->render('atelier/index.html.twig', [
            'ateliers' => $markdownAtelier->parseArray(
                $atelierRepository->findAll()),
            'apprenti' => ""
        ]);
    }

    #[Route('/new', name: 'app_atelier_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AtelierRepository $atelierRepository): Response
    {
        $atelier = new Atelier();
        $form = $this->createForm(AtelierType::class, $atelier);
        $form->handleRequest($request);

        $error = "";

        if ($this->getUser() === null) {
            $error = "Vous devez être connecté pour créer un nouvel atelier";

        }

        if ($form->isSubmitted() && $form->isValid() && in_array("ROLE_INSTRUCTOR", $this->getUser()->getRoles())) {
            $atelier->setNomInstructeur($this->getUser());
            $atelierRepository->save($atelier, true);

            return $this->redirectToRoute('app_atelier_index', ["apprenti" => ""], Response::HTTP_SEE_OTHER);
        }

        if ($form->isSubmitted() && !in_array("ROLE_INSTRUCTOR", $this->getUser()->getRoles())) {
            $error = "Votre role ne permet pas la création d'un nouvel atelier";

        }

        return $this->renderForm('atelier/new.html.twig', [
            'atelier' => $atelier,
            'form' => $form, 'error' => $error
        ]);
    }

    #[Route('/{id}', name: 'app_atelier_show', methods: ['GET'])]
    public function show(Atelier $atelier): Response
    {
        return $this->render('atelier/show.html.twig', [
            'atelier' => $atelier,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_atelier_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Atelier $atelier, AtelierRepository $atelierRepository): Response
    {
        $form = $this->createForm(AtelierType::class, $atelier);
        $form->handleRequest($request);
        $error = "";

        if ($form->isSubmitted() && $form->isValid() && $this->getUser() == $atelier->getNomInstructeur()) {
            $atelierRepository->save($atelier, true);

            return $this->redirectToRoute('app_atelier_index', ["apprenti" => ""], Response::HTTP_SEE_OTHER);
        }

        if ($form->isSubmitted() && $atelier->getNomInstructeur() != $this->getUser()) {
            $error = "Votre role ne permet pas la modification de cet atelier";

        }

        return $this->renderForm('atelier/edit.html.twig', [
            'atelier' => $atelier,
            'form' => $form,
            'error' => $error
        ]);
    }

    #[Route('/{id}', name: 'app_atelier_delete', methods: ['POST'])]
    public function delete(Request $request, Atelier $atelier, AtelierRepository $atelierRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $atelier->getId(), $request->request->get('_token'))) {
            $atelierRepository->remove($atelier, true);
        }

        return $this->redirectToRoute('app_atelier_itri', ["apprenti" => ""], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/inscrire', name: 'app_atelier_inscrire', methods: ['GET', 'POST'])]
    public function inscrire(Request $request, Atelier $atelier, AtelierRepository $atelierRepository, MarkdownAtelier $markdownAtelier): Response
    {


//        if( !in_array($this->getUser()->getId(),$atelier->getApprentisInscrits()) ){
        $atelier->addApprentiInscrit($this->getUser()->getId());
        $atelierRepository->save($atelier, true);


        return $this->render('atelier/index.html.twig', [
            "apprenti" => "Vous êtes inscrit à l'atelier " . $atelier->getNom(),
            'ateliers' => $markdownAtelier->parseArray(
                $atelierRepository->findAll())

        ]);
    }

    #[Route('/{id}/desinscrire', name: 'app_atelier_desinscrire', methods: ['GET', 'POST'])]
    public function desinscrire(Request $request, Atelier $atelier, AtelierRepository $atelierRepository, MarkdownAtelier $markdownAtelier): Response
    {


//        if( !in_array($this->getUser()->getId(),$atelier->getApprentisInscrits()) ){
        $atelier->removeApprentiInscrit($this->getUser()->getId());
        $atelierRepository->save($atelier, true);


        return $this->render('atelier/index.html.twig', [
            "apprenti" => "Vous êtes désinscrit à l'atelier " . $atelier->getNom(),
            'ateliers' => $markdownAtelier->parseArray(
                $atelierRepository->findAll())

        ]);
    }

    #[Route('/{id}/apprentis', name: 'app_atelier_apprentis', methods: ['GET'])]
    public function listeApprentis(Atelier $atelier, UserRepository $userRepository): Response
    {

        $users = $userRepository->findAll();
        $apprentis = [];
        for ($i = 0; $i < sizeof($users); $i++) {
            if (in_array($users[$i]->getId(), $atelier->getApprentisInscrits())) {
                array_push($apprentis, $users[$i]);
            }
        }
        return $this->render('atelier/apprentis.html.twig', [
            'apprentis' => $apprentis,
            'atelier' => $atelier->getNom()
        ]);

    }

    #[Route('/98/itri', name: 'app_atelier_apprentis1', methods: ['GET'])]
    public function listeApprentisitri(Atelier $atelier, UserRepository $userRepository): Response
    {


        return "itri";

    }






}

templates/atelier/_delete_form.html.twig
{% if app.user == atelier.nomInstructeur %}
    <form method="post" action="{{ path('app_atelier_delete', {'id': atelier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ atelier.id) }}">
        <br>
        <button class="btn btn-danger">Supprimer</button>
    </form>
{% else %}
    <form method="post" action="{{ path('app_atelier_edit',{'id': atelier.id}) }}" onsubmit="return confirm('Vous ne pouvez pas supprimer cet atelier');">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ atelier.id) }}">
        <br>
        <button class="btn btn-danger">Supprimer</button>
    </form>
{% endif %}

templates/atelier/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/atelier/accueil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Homepage{% endblock %}

{% block body %}
    <div class="container">
        <br><h1 class="titre">Welcome to the Homepage</h1><br>
        <p class="lorem">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce porttitor tristique leo eget mattis. Ut sed lorem ac nunc posuere consequat quis id libero. Morbi porttitor elementum augue eu tempor. Quisque in ex purus. Proin eu dolor tristique, blandit tellus in, dignissim quam. Curabitur commodo erat varius urna condimentum, et vehicula ipsum molestie. Maecenas suscipit ante ac justo placerat hendrerit. Suspendisse vehicula massa at lacus volutpat, ut rhoncus tortor elementum. Nullam faucibus ultricies magna, quis viverra massa commodo eget. Suspendisse a dui id felis placerat lobortis id at quam. Mauris ornare metus vel aliquet dapibus. Phasellus et vehicula augue. Phasellus vehicula lobortis libero, ac laoreet quam lobortis id. </p>

    </div>
{% endblock %}

templates/atelier/apprentis.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ateliers Inscrits{% endblock %}

{% block body %}

    <div class="container d-flex align-items-center justify-content-center">
        <div>
            <br>
            <h1>{{ atelier }}</h1>
            <br>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Login</th>
                    <th>Nom</th>
                    <th>Prénom</th>

                </tr>
                </thead>
                <tbody>
                {% for apprenti in apprentis %}
                    <tr>
                        <td>{{ apprenti.login }}</td>
                        <td>
                            {{ apprenti.nom }}
                        </td>
                        <td>
                            {{ apprenti.prenom }}
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="4">Aucun apprenti dans cet atelier</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
    <br>



{% endblock %}

templates/atelier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Atelier{% endblock %}

{% block body %}
    {% if error|length > 0 %}
        <div class="alert alert-danger">{{error}}</div>
    {% endif %}
    <div class="container ">
        <div>
            <br>
            <br>
            <h3>Modifier atelier</h3>
            <br>

            {{ include('atelier/_form.html.twig', {'button_label': 'Mise à jour'}) }}
            <br>
            <a href="{{ path('app_atelier_index') }}" class="btn btn-secondary" role="button" aria-pressed="true">Retour</a>


            {{ include('atelier/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/atelier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Atelier index{% endblock %}

{% block body %}

    {% if apprenti|length > 0 %}

        <div class="alert alert-success">{{apprenti}}</div>
    {% endif %}
<div class="container d-flex align-items-center justify-content-center">
    <div>
        <br>
            <h1>Ateliers</h1>
            <br>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Description</th>
                <th>Créateur</th>
            </tr>
        </thead>
        <tbody>
        {% for atelier in ateliers %}
            <tr>

                <td><a href="{{ path('app_atelier_show', {'id': atelier.id}) }}">{{ atelier.Nom }}</a></td>
                <td>
                    {{ atelier.description| u.truncate(100,' ...',false) |raw}}
                </td>
                <td>
                    {{ atelier.nomInstructeur.nom }}
                </td>
                <td>
                    {{ atelier.apprentisInscrits|length }}
                </td>
                <td>


                    <a href="{{ path('app_atelier_edit', {'id': atelier.id}) }}" class="btn btn-info" role="button" aria-pressed="true">Modifier</a>



                </td>
                <td>
                    {% if   app.user.id in atelier.apprentisInscrits %}
                    <a href="{{ path('app_atelier_desinscrire', {'id': atelier.id}) }}" class="btn btn-danger" role="button" aria-pressed="true">Desinscrire</a>
                    {% else %}
                        <a href="{{ path('app_atelier_inscrire', {'id': atelier.id}) }}" class="btn btn-success" role="button" aria-pressed="true">Inscrire</a>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('app_atelier_apprentis', {'id': atelier.id}) }}" class="btn btn-success" role="button" aria-pressed="true">Apprentis</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    </div>

        </div>
    <br>



{% endblock %}

templates/atelier/inscriptions.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscriptions{% endblock %}

{% block body %}

    {% if apprenti|length > 0 %}

        <div class="alert alert-success">{{apprenti}}</div>
    {% endif %}
    <div class="container d-flex align-items-center justify-content-center">
        <div>
            <br>
            <h1>Mes inscriptions</h1>
            <br>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Nom</th>
                    <th>Description</th>
                    <th>Créateur</th>
                </tr>
                </thead>
                <tbody>
                {% for atelier in mesAteliers %}
                    <tr>

                        <td>{{ atelier.Nom }}</td>
                        <td>
                            {{ atelier.description| u.truncate(100,' ...',false) |raw}}
                        </td>
                        <td>
                            {{ atelier.nomInstructeur.nom }}
                        </td>
                        <td>
                                <a href="{{ path('app_atelier_desinscrire', {'id': atelier.id}) }}" class="btn btn-danger" role="button" aria-pressed="true">Desinscrire</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="4">Vous n'êtes inscrit dans aucun atelier</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>

    </div>
    <br>



{% endblock %}

<h1>Bonjour</h1>

templates/atelier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Atelier{% endblock %}


{% block body %}
    {% if error|length > 0 %}

        <div class="alert alert-danger">{{error}}</div>
    {% endif %}
    <div class="container">
        <div>
            <br>
            <br>
            <h3>Créer Atelier</h3>
            <br>

            {{ include('atelier/_form.html.twig') }}
            <br>
            <a href="{{ path('app_atelier_index') }}" class="btn btn-secondary" role="button" aria-pressed="true">Retour</a>

        </div>
    </div>
{% endblock %}

templates/atelier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Atelier{% endblock %}

{% block body %}


<div class="container d-flex align-items-center justify-content-center">
    <div>
        <br>
    <h1>Atelier</h1>
        <br>

    <table class="table table-striped">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ atelier.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ atelier.Nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ atelier.Description }}</td>
            </tr>
        </tbody>
    </table>
        <div class="container-fluid">
            <a href="{{ path('app_atelier_edit', {'id': atelier.id}) }}" class="btn btn-success" role="button" aria-pressed="true">Edit</a>
            <a href="{{ path('app_atelier_index') }}" class="btn btn-secondary" role="button" aria-pressed="true">Retour</a>
            {{ include('atelier/_delete_form.html.twig') }}
        </div>


            </div>
        </div>

{% endblock %}